name: http_client_test
description: Test HTTP clients using a snapshot of the request and response
version: 0.0.0
homepage: https://github.com/SoftwareFreak1/http_client_test
repository: https://github.com/SoftwareFreak1/http_client_test

environment:
  sdk: ^3.0.0

dependencies:
  collection: ^1.17.1

dev_dependencies:
  build_runner: ^2.4.4
  lints: ^2.1.0
  mockito: ^5.4.0
  test: ^1.24.2
