name: http_client_test
description: Test HTTP clients using a snapshot of the request and response
publish_to: 'none'
version: 0.0.0

environment:
  sdk: ^3.0.0

dependencies:
  collection: ^1.17.2
  matcher: ^0.12.15
  test: ^1.24.1

dev_dependencies:
  build_runner: ^2.4.4
  lints: ^2.1.0
  mockito: ^5.4.0
