name: CI
on: [push]
jobs:
  static-code-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.0.0
      - run: dart format --set-exit-if-changed .
      - run: dart pub get
      - run: dart run build_runner build --delete-conflicting-outputs
      - run: dart analyze --fatal-infos
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.0.0
      - run: dart pub get
      - run: dart run build_runner build --delete-conflicting-outputs
      - run: dart test
      - run: dart test ./integration_test
  pana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.0.0
      - run: dart pub global activate pana
      - run: dart pub global run pana --no-warning --exit-code-threshold 0
